# Generated by Django 4.2.7 on 2025-08-27 15:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "min_invoice_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "max_invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "days_before_due",
                    models.IntegerField(
                        default=3,
                        help_text="Days before due date to send first reminder",
                    ),
                ),
                (
                    "days_after_due_1",
                    models.IntegerField(
                        default=1,
                        help_text="Days after due date for first overdue reminder",
                    ),
                ),
                (
                    "days_after_due_2",
                    models.IntegerField(
                        default=7,
                        help_text="Days after due date for second overdue reminder",
                    ),
                ),
                (
                    "days_after_due_3",
                    models.IntegerField(
                        default=15, help_text="Days after due date for final notice"
                    ),
                ),
                ("use_email", models.BooleanField(default=True)),
                ("use_sms", models.BooleanField(default=False)),
                ("skip_weekends", models.BooleanField(default=True)),
                ("skip_holidays", models.BooleanField(default=True)),
                (
                    "max_reminders",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["min_invoice_amount"],
            },
        ),
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("friendly", "Friendly"),
                            ("professional", "Professional"),
                            ("firm", "Firm"),
                            ("urgent", "Urgent"),
                            ("final_notice", "Final Notice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pre_due", "Before Due Date"),
                            ("due_date", "On Due Date"),
                            ("overdue_1", "Overdue - First Reminder"),
                            ("overdue_2", "Overdue - Second Reminder"),
                            ("overdue_3", "Overdue - Final Notice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email_subject", models.CharField(max_length=300)),
                (
                    "email_body",
                    models.TextField(
                        help_text="Use {{invoice_number}}, {{client_name}}, {{amount}}, {{due_date}} as placeholders"
                    ),
                ),
                (
                    "sms_message",
                    models.TextField(
                        help_text="SMS message (max 500 chars)", max_length=500
                    ),
                ),
                ("include_pdf_attachment", models.BooleanField(default=True)),
                ("include_payment_link", models.BooleanField(default=True)),
                ("include_payment_history", models.BooleanField(default=False)),
                ("include_late_fees", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "tone"],
                "unique_together": {("user", "tone", "stage")},
            },
        ),
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("pre_due", "Before Due Date"),
                            ("due_date", "On Due Date"),
                            ("overdue_1", "Overdue - First"),
                            ("overdue_2", "Overdue - Second"),
                            ("overdue_3", "Overdue - Final"),
                            ("manual", "Manual Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("skipped", "Skipped"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("custom_subject", models.CharField(blank=True, max_length=300)),
                ("custom_email_body", models.TextField(blank=True)),
                ("custom_sms_message", models.TextField(blank=True, max_length=500)),
                ("email_sent", models.BooleanField(default=False)),
                ("sms_sent", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_schedules",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "reminder_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.reminderrule",
                    ),
                ),
                (
                    "reminder_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.remindertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="due_date_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="due_date_rules",
                to="invoices.remindertemplate",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="overdue_1_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overdue_1_rules",
                to="invoices.remindertemplate",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="overdue_2_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overdue_2_rules",
                to="invoices.remindertemplate",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="overdue_3_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overdue_3_rules",
                to="invoices.remindertemplate",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="pre_due_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_due_rules",
                to="invoices.remindertemplate",
            ),
        ),
        migrations.AddField(
            model_name="reminderrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminder_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("both", "Email & SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=300)),
                ("email_body_preview", models.TextField(blank=True, max_length=500)),
                ("sms_message", models.TextField(blank=True, max_length=500)),
                ("email_delivered", models.BooleanField(default=False)),
                ("email_opened", models.BooleanField(default=False)),
                ("email_clicked", models.BooleanField(default=False)),
                ("sms_delivered", models.BooleanField(default=False)),
                ("client_responded", models.BooleanField(default=False)),
                ("payment_received", models.BooleanField(default=False)),
                ("payment_received_date", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "reminder_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="invoices.reminderschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ReminderAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_reminders_sent", models.IntegerField(default=0)),
                ("email_reminders_sent", models.IntegerField(default=0)),
                ("sms_reminders_sent", models.IntegerField(default=0)),
                ("invoices_paid_after_reminder", models.IntegerField(default=0)),
                (
                    "total_amount_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "average_days_to_payment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "best_template_success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "email_success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "sms_success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "best_performing_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.remindertemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="ClientReminderPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_email", models.EmailField(max_length=254)),
                ("client_name", models.CharField(max_length=200)),
                ("prefers_email", models.BooleanField(default=True)),
                ("prefers_sms", models.BooleanField(default=False)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_reminder_days",
                    models.IntegerField(default=3, help_text="Days before due date"),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("reminders_paused", models.BooleanField(default=False)),
                ("pause_until", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about client preferences"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "client_email")},
            },
        ),
    ]
