# Generated by Django 4.2.7 on 2025-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_reminderrule_remindertemplate_reminderschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="razorpay_payment_link_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
